// This file contains all your shop's menu data.
// We will use this to build the POS interface.

export const menuData = {
  // All prices are 10.00
  addons: [
    { id: 'pearl', name: 'Pearl', price: 10.00 },
    { id: 'fruit-jelly', name: 'Fruit Jelly', price: 10.00 },
    { id: 'nata', name: 'Nata', price: 10.00 },
    { id: 'coffee-jelly', name: 'Coffee Jelly', price: 10.00 },
    { id: 'creamcheese', name: 'Creamcheese', price: 10.00 },
    { id: 'crushed-oreo', name: 'Crushed Oreo', price: 10.00 },
    { id: 'crushed-graham', name: 'Crushed Graham', price: 10.00 },
    { id: 'coffee-shot', name: 'Coffee Shot', price: 10.00 },
  ],
  // Options that don't change the price - REMOVED
  
  // All your product categories
  categories: [
    {
      id: 'milktea',
      name: 'Milk Tea',
      products: [
        { id: 'mt-wintermelon', name: 'Wintermelon', prices: { medium: 28.00, large: 38.00 } },
        { id: 'mt-okinawa', name: 'Okinawa', prices: { medium: 28.00, large: 38.00 } },
        { id: 'mt-salted-caramel', name: 'Salted Caramel', prices: { medium: 28.00, large: 38.00 } },
        { id: 'mt-matcha', name: 'Matcha', prices: { medium: 28.00, large: 38.00 } },
        { id: 'mt-cheesecake', name: 'Cheesecake', prices: { medium: 28.00, large: 38.00 } },
        { id: 'mt-taro', name: 'Taro', prices: { medium: 28.00, large: 38.00 } },
        { id: 'mt-cookies-cream', name: 'Cookies & Cream', prices: { medium: 28.00, large: 38.00 } },
        { id: 'mt-caramel-macchiato', name: 'Caramel Macchiato', prices: { medium: 28.00, large: 38.00 } },
        { id: 'mt-cappuccino', name: 'Cappuccino', prices: { medium: 28.00, large: 38.00 } },
        { id: 'mt-mocha', name: 'Mocha', prices: { medium: 28.00, large: 38.00 } },
        { id: 'mt-dark-choco', name: 'Dark Choco', prices: { medium: 28.00, large: 38.00 } },
        { id: 'mt-double-dutch', name: 'Double Dutch', prices: { medium: 28.00, large: 38.00 } },
        { id: 'mt-rocky-road', name: 'Rocky Road', prices: { medium: 28.00, large: 38.00 } },
        { id: 'mt-choco-kisses', name: 'Choco Kisses', prices: { medium: 28.00, large: 38.00 } },
        { id: 'mt-black-forest', name: 'Black Forest', prices: { medium: 28.00, large: 38.00 } },
        { id: 'mt-red-velvet', name: 'Red Velvet', prices: { medium: 28.00, large: 38.00 } },
        { id: 'mt-hazelnut', name: 'Hazelnut', prices: { medium: 28.00, large: 38.00 } },
        { id: 'mt-milky-choco', name: 'Milky Choco', prices: { medium: 28.00, large: 38.00 } },
        { id: 'mt-avocado', name: 'Avocado', prices: { medium: 28.00, large: 38.00 } },
        { id: 'mt-buko-pandan', name: 'Buko Pandan', prices: { medium: 28.00, large: 38.00 } },
        { id: 'mt-melon', name: 'Melon', prices: { medium: 28.00, large: 38.00 } },
        { id: 'mt-strawberry', name: 'Strawberry', prices: { medium: 28.00, large: 38.00 } },
        { id: 'mt-ube', name: 'Ube', prices: { medium: 28.00, large: 38.00 } },
        { id: 'mt-mango', name: 'Mango', prices: { medium: 28.00, large: 38.00 } },
      ],
    },
    {
      id: 'fruit-tea',
      name: 'Fruit Tea',
      products: [
        { id: 'ft-lemonade', name: 'Lemonade', prices: { medium: 28.00, large: 38.00 } },
        { id: 'ft-black-tea-lemon', name: 'Black Tea Lemon', prices: { medium: 28.00, large: 38.00 } },
        { id: 'ft-lychee', name: 'Lychee', prices: { medium: 28.00, large: 38.00 } },
        { id: 'ft-green-apple', name: 'Green Apple', prices: { medium: 28.00, large: 38.00 } },
        { id: 'ft-strawberry', name: 'Strawberry', prices: { medium: 28.00, large: 38.00 } },
        { id: 'ft-blueberry', name: 'Blueberry', prices: { medium: 28.00, large: 38.00 } },
        { id: 'ft-kiwi', name: 'Kiwi', prices: { medium: 28.00, large: 38.00 } },
        { id: 'ft-grapes', name: 'Grapes', prices: { medium: 28.00, large: 38.00 } },
        { id: 'ft-passion-fruit', name: 'Passion Fruit', prices: { medium: 28.00, large: 38.00 } },
        { id: 'ft-mango', name: 'Mango', prices: { medium: 28.00, large: 38.00 } },
      ],
    },
    {
      id: 'soda',
      name: 'Soda Series',
      products: [
        { id: 'soda-lemonade', name: 'Lemonade', prices: { medium: 50.00, large: 60.00 } },
        { id: 'soda-lychee', name: 'Lychee', prices: { medium: 50.00, large: 60.00 } },
        { id: 'soda-green-apple', name: 'Green Apple', prices: { medium: 50.00, large: 60.00 } },
        { id: 'soda-strawberry', name: 'Strawberry', prices: { medium: 50.00, large: 60.00 } },
        { id: 'soda-kiwi', name: 'Kiwi', prices: { medium: 50.00, large: 60.00 } },
        { id: 'soda-blueberry', name: 'Blueberry', prices: { medium: 50.00, large: 60.00 } },
        { id: 'soda-passion-fruit', name: 'Passion Fruit', prices: { medium: 50.00, large: 60.00 } },
        { id: 'soda-mango', name: 'Mango', prices: { medium: 50.00, large: 60.00 } },
        { id: 'soda-coke-float', name: 'Coke Float', prices: { medium: 40.00 } }, // Only one size
      ],
    },
    {
      id: 'milk-series',
      name: 'Milk Series',
      products: [
        { id: 'ms-strawberry', name: 'Strawberry', prices: { medium: 58.00, large: 68.00 } },
        { id: 'ms-blueberry', name: 'Blueberry', prices: { medium: 58.00, large: 68.00 } },
        { id: 'ms-mango', name: 'Mango', prices: { medium: 58.00, large: 68.00 } },
        { id: 'ms-ube', name: 'Ube', prices: { medium: 58.00, large: 68.00 } },
        { id: 'ms-dark-choco', name: 'Dark Choco', prices: { medium: 58.00, large: 68.00 } },
        { id: 'ms-double-dutch', name: 'Double Dutch', prices: { medium: 58.00, large: 68.00 } },
        { id: 'ms-rocky-road', name: 'Rocky Road', prices: { medium: 58.00, large: 68.00 } },
        { id: 'ms-choco-kisses', name: 'Choco Kisses', prices: { medium: 58.00, large: 68.00 } },
        { id: 'ms-black-forest', name: 'Black Forest', prices: { medium: 58.00, large: 68.00 } },
        { id: 'ms-red-velvet', name: 'Red Velvet', prices: { medium: 58.00, large: 68.00 } },
        { id: 'ms-hazelnut', name: 'Hazelnut', prices: { medium: 58.00, large: 68.00 } },
        { id: 'ms-milky-choco', name: 'Milky Choco', prices: { medium: 58.00, large: 68.00 } },
        { id: 'ms-wintermelon', name: 'Wintermelon', prices: { medium: 58.00, large: 68.00 } },
        { id: 'ms-okinawa', name: 'Okinawa', prices: { medium: 58.00, large: 68.00 } },
        { id: 'ms-salted-caramel', name: 'Salted Caramel', prices: { medium: 58.00, large: 68.00 } },
        { id: 'ms-matcha', name: 'Matcha', prices: { medium: 58.00, large: 68.00 } },
        { id: 'ms-cheesecake', name: 'Cheesecake', prices: { medium: 58.00, large: 68.00 } },
        { id: 'ms-taro', name: 'Taro', prices: { medium: 58.00, large: 68.00 } },
        { id: 'ms-cookies-cream', name: 'Cookies & Cream', prices: { medium: 58.00, large: 68.00 } },
        { id: 'ms-mocha', name: 'Mocha', prices: { medium: 58.00, large: 68.00 } },
      ],
    },
    {
      id: 'frappe',
      name: 'Frappe',
      products: [
        { id: 'f-wintermelon', name: 'Wintermelon', prices: { medium: 50.00, large: 70.00 } },
        { id: 'f-okinawa', name: 'Okinawa', prices: { medium: 50.00, large: 70.00 } },
        { id: 'f-salted-caramel', name: 'Salted Caramel', prices: { medium: 50.00, large: 70.00 } },
        { id: 'f-matcha', name: 'Matcha', prices: { medium: 50.00, large: 70.00 } },
        { id: 'f-cheesecake', name: 'Cheesecake', prices: { medium: 50.00, large: 70.00 } },
        { id: 'f-taro', name: 'Taro', prices: { medium: 50.00, large: 70.00 } },
        { id: 'f-cookies-cream', name: 'Cookies & Cream', prices: { medium: 50.00, large: 70.00 } },
        { id: 'f-caramel-macchiato', name: 'Caramel Macchiato', prices: { medium: 50.00, large: 70.00 } },
        { id: 'f-cappuccino', name: 'Cappuccino', prices: { medium: 50.00, large: 70.00 } },
        { id: 'f-mocha', name: 'Mocha', prices: { medium: 50.00, large: 70.00 } },
        { id: 'f-ube', name: 'Ube', prices: { medium: 50.00, large: 70.00 } },
        { id: 'f-melon', name: 'Melon', prices: { medium: 50.00, large: 70.00 } },
        { id: 'f-avocado', name: 'Avocado', prices: { medium: 50.00, large: 70.00 } },
        { id: 'f-buko-pandan', name: 'Buko Pandan', prices: { medium: 50.00, large: 70.00 } },
        { id: 'f-strawberry', name: 'Strawberry', prices: { medium: 50.00, large: 70.00 } },
        { id: 'f-blueberry', name: 'Blueberry', prices: { medium: 50.00, large: 70.00 } },
        { id: 'f-mango-graham', name: 'Mango Graham', prices: { medium: 50.00, large: 70.00 } },
        { id: 'f-dark-choco', name: 'Dark Choco', prices: { medium: 50.00, large: 70.00 } },
        { id: 'f-double-dutch', name: 'Double Dutch', prices: { medium: 50.00, large: 70.00 } },
        { id: 'f-choco-kisses', name: 'Choco Kisses', prices: { medium: 50.00, large: 70.00 } },
        { id: 'f-black-forest', name: 'Black Forest', prices: { medium: 50.00, large: 70.00 } },
        { id: 'f-red-velvet', name: 'Red Velvet', prices: { medium: 50.00, large: 70.00 } },
        { id: 'f-hazelnut', name: 'Hazelnut', prices: { medium: 50.00, large: 70.00 } },
        { id: 'f-milky-choco', name: 'Milky Choco', prices: { medium: 50.00, large: 70.00 } },
      ],
    },
    {
      id: 'iced-coffee',
      name: 'Iced Coffee',
      products: [
        { id: 'ic-latte', name: 'Iced Coffee Latte', prices: { medium: 38.00, large: 48.00 } },
        { id: 'ic-caramel-macchiato', name: 'Iced Caramel Macchiato', prices: { medium: 38.00, large: 48.00 } },
        { id: 'ic-mocha', name: 'Iced Coffee Mocha', prices: { medium: 38.00, large: 48.00 } },
        { id: 'ic-caramel-mocha', name: 'Iced Caramel Mocha', prices: { medium: 38.00, large: 48.00 } },
        { id: 'ic-americano', name: 'Iced Americano', prices: { medium: 38.00, large: 48.00 } },
        { id: 'ic-vanilla', name: 'Iced Coffee Vanilla', prices: { medium: 38.00, large: 48.00 } },
      ],
    },
    {
      id: 'latte-series',
      name: 'Latte Series',
      products: [
        { id: 'l-strawberry', name: 'Strawberry Latte', prices: { medium: 58.00, large: 68.00 } },
        { id: 'l-matcha', name: 'Matcha Latte', prices: { medium: 58.00, large: 68.00 } },
        { id: 'l-blueberry', name: 'Blueberry Latte', prices: { medium: 58.00, large: 68.00 } },
        { id: 'l-spanish', name: 'Spanish Latte', prices: { medium: 68.00, large: 78.00 } },
        { id: 'l-lotus-biscoff', name: 'Lotus Biscoff Latte', prices: { medium: 78.00, large: 88.00 } },
      ],
    },
    {
      id: 'non-coffee',
      name: 'Non-Coffee',
      products: [
        { id: 'nc-cocoa', name: 'Cocoa Latte', prices: { medium: 78.00, large: 88.00 } },
        { id: 'nc-matcha-berry', name: 'Matcha Berry Latte', prices: { medium: 78.00, large: 88.00 } },
      ],
    },
    {
      id: 'hot-drinks',
      name: 'Hot Drinks',
      products: [
        { id: 'h-hot-choco', name: 'Hot Choco', prices: { medium: 48.00 } },
        { id: 'h-caramel-macchiato', name: 'Caramel Macchiato', prices: { medium: 48.00 } },
        { id: 'h-cappuccino', name: 'Cappuccino', prices: { medium: 48.00 } },
        { id: 'h-matcha-coffee', name: 'Matcha Coffee', prices: { medium: 48.00 } },
        { id: 'h-cocoa-latte', name: 'Hot Cocoa Latte', prices: { medium: 78.00 } },
      ],
    },
    {
      id: 'yogurt-series',
      name: 'Yogurt Series',
      products: [
        { id: 'y-milk', name: 'Yogurt Milk', prices: { medium: 68.00, large: 78.00 } },
        { id: 'y-strawberry', name: 'Strawberry', prices: { medium: 68.00, large: 78.00 } },
        { id: 'y-blueberry', name: 'Blueberry', prices: { medium: 68.00, large: 78.00 } },
        { id: 'y-mango', name: 'Mango', prices: { medium: 68.00, large: 78.00 } },
        { id: 'y-green-apple', name: 'Green Apple', prices: { medium: 68.00, large: 78.00 } },
      ],
    },
    {
      id: 'fruit-tea-yogurt',
      name: 'Fruit Tea Yogurt',
      // Assuming prices are the same as Yogurt Series
      products: [
        { id: 'fty-lemonade', name: 'Lemonade', prices: { medium: 68.00, large: 78.00 } },
        { id: 'fty-lychee', name: 'Lychee', prices: { medium: 68.00, large: 78.00 } },
        { id: 'fty-strawberry', name: 'Strawberry', prices: { medium: 68.00, large: 78.00 } },
        { id: 'fty-blueberry', name: 'Blueberry', prices: { medium: 68.00, large: 78.00 } },
        { id: 'fty-mango', name: 'Mango', prices: { medium: 68.00, large: 78.00 } },
      ],
    },
  ],
};